name: med_assist
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  custom_pin_screen: ^0.3.0
  firebase_auth: ^5.5.1
  flutter:
    sdk: flutter
  intl: ^0.17.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  provider: ^6.1.2
  local_auth: ^2.3.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.2.1
  flutter_local_notifications: ^19.0.0
  rxdart: ^0.28.0
  alarm: ^5.1.1
  uuid: ^4.5.1
  supabase_flutter: ^2.8.4
  url_launcher: ^6.3.1
  file_picker: ^10.1.2
  mime: ^2.0.0
  flutter_pdfview: ^1.4.0+1
  photo_view: ^0.15.0
  open_filex: ^4.7.0
  dio: ^5.4.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/alarm.wav
