name: med_assist
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  custom_pin_screen: ^0.3.0
  firebase_auth: ^5.5.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  provider: ^6.1.2
  local_auth: ^2.3.0
  persistent_bottom_nav_bar: ^6.2.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
